baseURL = "http://example.org/"
languageCode = "en-us"
title = "gniqizeuy blog"
theme = "book"
PygmentsCodeFences = true
PygmentsStyle = "perldoc"
[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'